management.endpoints.web.exposure.include: health,info,metrics

spring:
  application:
    name: data-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DATABASE_IP}:3306/${MYSQL_DATABASE_NAME}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs.enabled: true
  swagger-ui.supported-submit-methods: [] # Disables "try it out" in the UI